### ISSUE TITLE
svelte-jsoneditor build

### ISSUE THREAD

**Issue by cornorghost** [bestkolobok/vue3-jsoneditor#11]
I'm trying to make json tool with svelte-jsoneditor, can u share the code how to build the svelte-jsoneditor into vue3? i need to customize some module in the svelte-jsoneditor project,  and build as a npm module , use in my vue3 project, thank

**Comment by bestkolobok** [comment]
All code to deploy and publish npm package is in this repository. You can use this. Run one of the npm scripts to run deploy and publish:

```
    "deploy": "sh deploy.sh patch",
    "deploy:minor": "sh deploy.sh minor",
    "deploy:major": "sh deploy.sh major",
```

or use pipeline from [this](https://github.com/bestkolobok/vue3-jsoneditor/blob/main/deploy.sh) file

**Comment by cornorghost** [comment]
> All code to deploy and publish npm package is in this repository. You can use this. Run one of the npm scripts to run deploy and publish:
> 
> ```
>     "deploy": "sh deploy.sh patch",
>     "deploy:minor": "sh deploy.sh minor",
>     "deploy:major": "sh deploy.sh major",
> ```
> 
> or use pipeline from [this](https://github.com/bestkolobok/vue3-jsoneditor/blob/main/deploy.sh) file
> 
> Also, I plan to release several updates of this package in the near future

thanks for replying, if i want to make the treeContexMenu into chinese, what should i do, i cannot find the 'Edit value' placement in the code

**Comment by bestkolobok** [comment]
Regarding the adding Chinese localization, you can ask the author  [svelte-jsoneditor](https://www.npmjs.com/package/svelte-jsoneditor). If he can implement it, then I will also implement it in my project

**Comment by cornorghost** [comment]
> Regarding the adding Chinese localization, you can ask the author [svelte-jsoneditor](https://www.npmjs.com/package/svelte-jsoneditor). If he can implement it, then I will also implement it in my project

i think i know the way, thank
