### ISSUE TITLE
Could not find a declaration file for module 'vue3-ts-jsoneditor'.

### ISSUE THREAD

**Issue by throrin19** [bestkolobok/vue3-jsoneditor#12]
Hello,

With the latest version it seems the build does not return plugin types like declared in the `package.json` : https://github.com/bestkolobok/vue3-jsoneditor/blob/049753aae4e20e55ef5ce0567d937880c637ea98/package.json#L21

If we look in the installed module, we don't have `dist/JsonEditorPlugin.d.ts` and our  builder return this error : 

```
 ERROR(vue-tsc)  Could not find a declaration file for module 'vue3-ts-jsoneditor'. '/my-project/node_modules/vue3-ts-jsoneditor/dist/index.mjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/vue3-ts-jsoneditor` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue3-ts-jsoneditor';`
 FILE  /my-project/src/App.vue:102:27

  > 102 | import VueJsoneditor from 'vue3-ts-jsoneditor';
        |                           ^^^^^^^^^^^^^^^^^^^^
    103 | import { useSnackbar } from 'vue3-snackbar';

[vue-tsc] Found 1 error. Watching for file changes.
```
![image](https://github.com/bestkolobok/vue3-jsoneditor/assets/1394778/5ea22107-49c8-41f2-907f-353e4278c2a6)

I'm using version `2.10.0`

**Comment by bestkolobok** [comment]
Hello! 

Thanks for this bug report. 
I fixed the type generation in version 2.10.1

**Comment by QuentinHsu** [comment]
> Hello!
> 
> Thanks for this bug report. I fixed the type generation in version 2.10.1

I found that this issue still exists in version 2.10.1.

```console
error TS7016: Could not find a declaration file for module 'vue3-ts-jsoneditor'. 'my-project/node_modules/.pnpm/vue3-ts-jsoneditor@2.10.1_@lezer+common@1.2.1_typescript@5.3.3/node_modules/vue3-ts-jsoneditor/dist/index.mjs' implicitly has an 'any' type.
  There are types at 'my-project/node_modules/vue3-ts-jsoneditor/dist/JsonEditorPlugin.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue3-ts-jsoneditor' library may need to update its package.json or typings.

2 import VueJsoneditor from 'vue3-ts-jsoneditor'
```

**Comment by bestkolobok** [comment]
> I found that this issue still exists in version 2.10.1.
> 
> ```
> error TS7016: Could not find a declaration file for module 'vue3-ts-jsoneditor'. 'my-project/node_modules/.pnpm/vue3-ts-jsoneditor@2.10.1_@lezer+common@1.2.1_typescript@5.3.3/node_modules/vue3-ts-jsoneditor/dist/index.mjs' implicitly has an 'any' type.
>   There are types at 'my-project/node_modules/vue3-ts-jsoneditor/dist/JsonEditorPlugin.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue3-ts-jsoneditor' library may need to update its package.json or typings.
> 
> 2 import VueJsoneditor from 'vue3-ts-jsoneditor'
> ```

I tried to reproduce this bug, so in version 2.10.0 it is present, but in version 2.10.1 I don't have it anymore, because there is already a generated **JsonEditorPlugin.d.ts** file. So, try to remove **node_modules**, and if it doesn't help, then add the .npmrc file to the root of your project:
```npm
shamefully-hoist=true
```


If that doesn't help then let me know and I will look into the issue

**Comment by throrin19** [comment]
I confirm I don't have any problem in 2.10.1

**Comment by CedrikHarrich** [comment]
Hello :)

Sadly I sill have the same issue in version 2.10.1. 
I tried to reinstall the node_modules and adding the npmrc file.

**Comment by bestkolobok** [comment]
Hi @CedrikHarrich ))

So far, it's hard for me to say what's causing the import error you're getting, as I can't reproduce it myself. I will further investigate this issue.
Firstly, try to update vue volar plugin for your IDE or [install it](https://www.npmjs.com/package/@vue/language-server) directly in your project 
For now, temporarily you can use the following solutions:
`import type { JsonEditorPlugin } from 'vue3-ts-jsoneditor/dist/JsonEditorPlugin';`

or add to tsconfig.json
```
"include": [
    "node_modules/vue3-ts-jsoneditor/dist/*.d.ts",
    // other files or directories you want to include
  ]
```

**Comment by CedrikHarrich** [comment]
@bestkolobok Thank you for this tip. If I can locate the problem, I will let you know.
So far, at least for my project, it has been good enough to put //@ts-ignore in front of the import, even if its not the purpose of Ts.

**Comment by bestkolobok** [comment]
Hi @CedrikHarrich,
I've updated the type generation for the JsonEditorPlugin.d.ts file and added an additional path to the types in the 'exports' section of the package.json. Perhaps this will help, since I could not reproduce this problem locally. So, try upgrading to 2.10.4

**Comment by CedrikHarrich** [comment]
Hello.
I tried it out. It does not give me the TS7016 when trying to build my files. However, it does not display the JsonEditor at all now. The <div class="vue-ts-json-editor"> is just missing in the dom. I did not get any error messages... 
I am using the  local variant in a component. Does that maybe make a difference?

**Comment by bestkolobok** [comment]
> ,

This was an issue with the default export ащк component after the previous release. Just fixed it so it works now.
Also, for better support of props typing, I had to change the export of the plugin:
`import {JsonEditorPlugin} from 'vue3-ts-jsoneditor';`

The component as before with default export:
`<script setup>
  import JsonEditor from 'vue3-ts-jsoneditor';
</script>`

**Comment by bestkolobok** [comment]
> I was trying out the demo link in the ReadMe. The server answers with a 404. It seems some js file was not compiled to ./assets. Maybe related?

This is a problem with the deployment of one of the assets. Fixed it temporarily. It is already working

**Comment by CedrikHarrich** [comment]
Thank you very much. It works. 👍
