### ISSUE TITLE
Bug: jsonString example don't work

### ISSUE THREAD

**Issue by Tibike6** [bestkolobok/vue3-jsoneditor#4]
When I try the example with jsonString I get an error: 
> Error: Content must contain either a property "json" or a property "text" but not both from vanilla-jsoneditor.js:30181

Example:
```
<template>
    <vue-jsoneditor height="400" :mode="mode" v-model:jsonString="state.jsonString" />
</template>

<script setup lang="ts">
import vueJsoneditor from 'vue3-ts-jsoneditor';
import 'vue3-ts-jsoneditor/styles.css';
import { reactive, ref } from 'vue';

const state = reactive({
    jsonString: JSON.stringify({
        array: [1, 2, 3],
        boolean: true,
        Null: null,
        number: 123,
        object: { a: 'b', c: 'd' },
        string: 'Hello World',
    })
});

const mode = ref('tree');
</script>
```
Tree view:
![image](https://user-images.githubusercontent.com/26546359/184106193-71e4744a-a929-4e9e-be5c-60bbb1ac7078.png)

Text view:
![image](https://user-images.githubusercontent.com/26546359/184106383-dc257060-14f6-482f-a193-fe2372b23bf1.png)

**Comment by bestkolobok** [comment]
Fixed in version 2.3.3. 

Keep in mind that `v-model:jsonString` two-way binding only works for `mode: "text"`
