### ISSUE TITLE
The cursor will jump to the front when the value changes

### ISSUE THREAD

**Issue by martaintao** [bestkolobok/vue3-jsoneditor#5]
```typescript
    const updateContent = (): void => {
      editor.value.set(content.value);
    };

    watch(() => props, updateProps, {deep: true});

    watch(() => props.json, updateContent, {deep: true});
```

**Comment by bestkolobok** [comment]
Hi! 

The problem is solved. 
Changes were also made to the data bindings from v-model:json/v-model:jsonString to v-model. Older bindings are still supported for backwards compatibility as well. See updated documentation: https://github.com/bestkolobok/vue3-jsoneditor/blob/main/README.md
