### ISSUE TITLE
:json prop does not support Array type

### ISSUE THREAD

**Issue by vivid-lamp** [bestkolobok/vue3-jsoneditor#7]
When I pass array [1,2,3] to :json prop, it parse this array incorrect.

![image](https://user-images.githubusercontent.com/42366916/226264675-b96d2aa0-8c26-435f-815f-9f0925358a34.png)

![image](https://user-images.githubusercontent.com/42366916/226264535-416de4ef-c5e6-48f8-a9ea-339d8f3b55b8.png)

**Comment by bestkolobok** [comment]
Hi!

Thanks for finding this bug. Already fixed it and updated the basic package https://github.com/josdejong/svelte-jsoneditor with the addition of new functionality.

Also, note that in 'text' mode you should use props 'text', and in 'tree' mode you should use props json

**Comment by bestkolobok** [comment]
Hi, @vivid-lamp! 

If your question is resolved, please close this issue
