### ISSUE TITLE
New functions need to expose from svelte-jsoneditor methods

### ISSUE THREAD

**Issue by exVimJack** [bestkolobok/vue3-jsoneditor#8]
https://www.npmjs.com/package/svelte-jsoneditor

refresh(): Promise<void>. Refresh rendering of the contents, for example after changing the font size. This is only available in text mode.
validate() : ContentErrors | null. Get all current parse errors and validation errors.
focus(): Promise<void>. Give the editor focus.
destroy(): Promise<void>. Destroy the editor, remove it from the DOM.

**Comment by bestkolobok** [comment]
Hi, @exVimJack!

I've updated the expose set to match the current list of https://www.npmjs.com/package/svelte-jsoneditor
