### ISSUE TITLE
I hope to add this prop,thx~

### ISSUE THREAD

**Issue by GenerQAQ** [bestkolobok/vue3-jsoneditor#9]
askToFormat: boolean When true (default), the user will be asked whether he/she wants to format the JSON document when a compact document is loaded or pasted in 'text' mode. Only applicable to 'text' mode.

**Comment by bestkolobok** [comment]
Hi @GenerQAQ ! Thanks for the suggested improvement and adding the description to the documentation. I have confirmed your pull request. Today I will make a release for NPM
